import { instance } from "@/api/axiosConfig";

import { VacancyQueryCardData } from "./types";
import { VacancyCardData } from "@/components/VacancyCard/types";
import { CreateVacancyParams } from "@/pages/Company/components/CreateVacancyFormModal/types";

export const VacanciesService = {
	// getAll: async (page: number) => instance.get("/vacancies/all", { params: [{ page }] }),
	// getAll: async (page: number): Promise<VacancyCardData[]> => [
	// 	{
	// 		description: "test etste",
	// 		id: "test1",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test1",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// 	{
	// 		description: "test etste",
	// 		id: "test",
	// 		tags: [{ value: "test", label: "test" }],
	// 		title: "test",
	// 		salary: { amount: "200", currency: "euros", inTime: "hour" },
	// 	},
	// ],
	delete: async (id: string) => instance.post("/vacancies/delete", id),
	create: async (data: CreateVacancyParams) => instance.post("/vacancies/create", data),
	// update: async (id: string, data: VacancyQueryCardData): Promise<VacancyQueryCardData> =>
	// 	instance.post("/vacancies/update", data, { params: [{ id }] }),
	update: async (id: string, data: VacancyQueryCardData): Promise<VacancyQueryCardData> => ({
		description: "test etste",
		id: "test1",
		tags: ["test"],
		title: "test45",
		salary: { amount: "200", currency: "euros", inTime: "hour" },
	}),
	// getVacancyiesForCompany: async (id: string, page: number): Promise<VacancyCardData[]> =>
	// 	instance.post(`/vacancies/vacacny/${id}`, page),
	getVacancyiesForCompany: async (id: string, page: number): Promise<VacancyCardData[]> => [
		{
			description: "test etste",
			id: "test1",
			tags: [{ value: "test", label: "test" }],
			title: "test1",
			countOfResponse: 10,
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "test etste",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
		{
			description: "LAST",
			id: "test",
			tags: [{ value: "test", label: "test" }],
			title: "test",
			salary: { amount: "200", currency: "euros", inTime: "hour" },
		},
	],
};
