version: '3'
services:
  host:
    build: 
      context: .
    ports:
      - "5000:5000"
    networks:
      employment_net:

  profile:
    build: 
      context: .
    ports:
      - "5001:5001"
    networks:
      employment_net:

  vacancies:
    build: 
      context: .
    ports:
      - "5002:5002"
    networks:
      employment_net:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - host
      - profile
      - vacancies
    networks:
      employment_net:

networks:
  employment_net:
    driver: bridge
    name: employment_net
