import { instance } from "@/api/axiosConfig";
import { FiltersProps } from "@/components/Filters/types";
import { VacnacyCardProps } from "@/components/VacancyCard/types";
import { VacancyProps } from "../vacancy/types";

export const VacancyService = {
	// getVacancies: async (filters: FiltersProps[] | []): Promise<VacnacyCardProps[] | []> =>
	// 	instance.post("/vacancies", { filters }),
	getVacancies: async (filters: FiltersProps[] | []): Promise<VacnacyCardProps[] | []> => [
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "1",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "2",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "1",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "3",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "4",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "5",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "6",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "7",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "8",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "9",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "10",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "11",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "12",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "13",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "14",
			postedTime: "25",
		},
		{
			companyTitle: "CompanyTitle",
			countCandidates: 25,
			description: "test etst etstet",
			isLiked: true,
			salary: { amount: "250", inTime: "hour", currency: "rubles" },
			tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
			vacancyTitle: "VacancyTitle",
			id: "15",
			postedTime: "25",
		},
	],

	//getVacancy: async (id: string): Promise<VacancyProps> => instance.post(`/vacancy/${id}`),
	getVacancy: async (id: string): Promise<VacancyProps> => ({
		companyTitle: "CompanyTitle",
		countCandidates: 25,
		description: "test etst etstet",
		companyFounded: "January 6, 1997",
		location: "London, England",
		salary: { amount: "250", inTime: "hour", currency: "rubles" },
		tags: [{ title: "test1" }, { title: "test2" }, { title: "test3" }],
		vacancyTitle: "VacancyTitle",
		id: "1",
		postedTime: "25",
	}),

	// liked: async (id: string): Promise<boolean> => instance.post("/vacancy/liked", { id }),

	liked: async (): Promise<boolean> => instance.get("/greet/hello"),
};
