import { instance } from "@/api/axiosConfig";
import { VacnacyCardProps } from "@/components/VacancyCard/types";
import { VacancyProps } from "./types";
// import { FiltersResponseData } from "../filters/types";
// import { FiltersProps } from "@/components";
import { FiltersResponseData } from "../filters";

export const VacancyService = {
	getVacancies: async ({
		filters,
		pageInfo,
	}: FiltersResponseData): Promise<VacnacyCardProps[] | []> =>
		instance.post("/vacancies/filters/search", { filters }),
	// getVacancies: async (filters: FiltersResponseData): Promise<VacnacyCardProps[] | []> => [
	// 	{
	// 		companyTitle: "CompanyTitle1",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "1",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle2",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "2",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle3",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "1",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle4",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "3",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle5",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "4",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle6",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "5",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle7",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "6",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle8",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "7",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle9",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "8",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle10",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "9",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle11",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "10",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle12",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "11",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle13",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "12",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle14",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "13",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle15",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "14",
	// 		postedTime: "25",
	// 	},
	// 	{
	// 		companyTitle: "CompanyTitle16",
	// 		countCandidates: 25,
	// 		description: "test etst etstet",
	// 		isLiked: true,
	// 		salary: { amount: "250", inTime: "hour", currency: "rubles" },
	// 		tags: [
	// 			{ title: "test1", color: "blue" },
	// 			{ title: "test2", color: "violet" },
	// 			{ title: "test3", color: "green" },
	// 		],
	// 		vacancyTitle: "VacancyTitle",
	// 		id: "15",
	// 		postedTime: "25",
	// 	},
	// ],

	//getVacancy: async (id: string): Promise<VacancyProps> => instance.post(`/vacancy/${id}`),
	getVacancy: async (id: string): Promise<VacancyProps> => ({
		companyTitle: "CompanyTitle",
		countCandidates: 25,
		description: "test etst etstet",
		companyFounded: "January 6, 1997",
		location: "London, England",
		salary: { amount: "250", inTime: "hour", currency: "rubles" },
		tags: [
			{ title: "test1", color: "blue" },
			{ title: "test2", color: "violet" },
			{ title: "test3", color: "green" },
		],
		vacancyTitle: "VacancyTitle",
		id: "1",
		postedTime: "25",
	}),

	// liked: async (id: string): Promise<boolean> => instance.post("/vacancy/liked", { id }),

	liked: async (): Promise<boolean> => instance.get("/greet/hello"),
};
